# Generated by Django 4.0.1 on 2022-03-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shopapp', '0002_product_remove_contact_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='null', max_length=13, null=True),
        ),
    ]
