# Generated by Django 4.0.1 on 2022-03-21 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('e_shopapp', '0004_remove_contact_id_contact_message_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='message_id',
        ),
        migrations.AddField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
