# Generated by Django 4.0.1 on 2022-03-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shopapp', '0005_remove_contact_message_id_contact_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=111)),
                ('address', models.CharField(max_length=111)),
                ('city', models.CharField(max_length=30)),
                ('zip_code', models.CharField(max_length=11)),
                ('phone_number', models.CharField(max_length=13)),
            ],
        ),
    ]
