# Generated by Django 4.0.1 on 2022-03-26 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_shopapp', '0006_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='zip_code',
            new_name='zip',
        ),
    ]
