# Generated by Django 4.0.1 on 2022-03-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shopapp', '0008_alter_orders_address_alter_orders_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=400)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
