# Generated by Django 4.0.1 on 2022-03-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shopapp', '0009_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='product_list_for_checkout',
            field=models.CharField(default='', max_length=500),
        ),
    ]
