# Generated by Django 4.0.1 on 2022-03-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shopapp', '0010_orders_product_list_for_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='null', max_length=44, null=True)),
                ('last_name', models.CharField(default='null', max_length=44, null=True)),
                ('address', models.CharField(default='null', max_length=111, null=True)),
                ('address2', models.CharField(default='null', max_length=111, null=True)),
                ('city', models.CharField(default='null', max_length=44, null=True)),
                ('zip', models.CharField(default='null', max_length=44, null=True)),
            ],
        ),
    ]
