# Generated by Django 4.0.1 on 2022-03-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shopapp', '0011_user_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='phone_number',
            field=models.CharField(default='null', max_length=13, null=True),
        ),
    ]
