# Generated by Django 4.0.1 on 2022-03-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shopapp', '0012_user_details_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_name',
            field=models.CharField(default='null', max_length=44, null=True),
        ),
    ]
