# Generated by Django 4.0.1 on 2022-03-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shopapp', '0013_product_seller_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller_name',
            field=models.CharField(default='e_shop', max_length=44, null=True),
        ),
    ]
