# Generated by Django 4.0.1 on 2022-03-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shopapp', '0014_alter_product_seller_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='image',
            field=models.ImageField(default='shop/user_profile_default_image/user_profile_default_image.png', upload_to='shop/user_profile_images'),
        ),
    ]
