# Generated by Django 4.0.1 on 2022-04-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shopapp', '0019_alter_user_details_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='image',
            field=models.ImageField(upload_to='media/shop/user_profile_images'),
        ),
    ]
