# Generated by Django 4.0.1 on 2022-04-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shopapp', '0022_alter_user_details_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='image',
            new_name='user_image',
        ),
        migrations.AlterField(
            model_name='product',
            name='publish_date',
            field=models.DateField(null=True),
        ),
    ]
