# Generated by Django 4.0.1 on 2022-04-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shopapp', '0025_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total_price',
            field=models.CharField(default='null', max_length=999999),
        ),
    ]
